#!/bin/sh

/app/dropbox download /acayrin/users /app/panel/data
mkdir server
chmod -R 777 server
/app/dropbox download /acayrin/server/backup.zip /app/backup.zip
unzip -o backup.zip
rm backup.zip
/app/dropbox download /acayrin/run.startup
chmod 777 run.startup
/app/run.startup
screen -S system.backup -dm bash -c "while true; do /app/uploader; sleep 600; done"
exit
