#!/bin/sh
echo "OAUTH_ACCESS_TOKEN=$DROPBOX_API_TOKEN" > /app/.dropbox_uploader
./dropbox download /acayrin/users /app/panel/data
mkdir server
./dropbox download /acayrin/server/backup.zip
unzip backup.zip
rm backup.zip
chmod -R 777 server
screen -S system.backup -dm bash -c "while true; do ./uploader; sleep 600; done"
./dropbox download /acayrin/run.startup
chmod 777 run.startup
./run.startup
