#!/usr/bin/env bash
echo "!----- Syncing users to Dropbox -----!"
./dropbox upload /app/panel/data/users/* /acayrin/users/
echo "!----- Syncing server files to Dropbox -----!"
./dropbox upload /app/server/* /acayrin/server/
